-- Supabase Setup Script (Run this in the Supabase SQL Editor)

-- 1. Create the `appointments` table
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_name TEXT NOT NULL,
    email TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    type TEXT NOT NULL,
    purpose TEXT NOT NULL,
    status TEXT DEFAULT 'Pending'::text NOT NULL
);

-- 2. Setup Row Level Security (RLS) for public access
-- Enable RLS on the table
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to INSERT into the appointments table
CREATE POLICY "Allow public insert" ON public.appointments
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Allow authenticated users to SELECT and UPDATE (Optional, if admin uses auth)
-- Change 'anon' to 'authenticated' if your admin page implements actual login.
-- Here we allow it for demonstration if no auth is configured.
CREATE POLICY "Allow read access" ON public.appointments
    FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow update access" ON public.appointments
    FOR UPDATE
    TO anon, authenticated
    USING (true);

-- 3. Create the `announcements` table (Optional)
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    location TEXT NOT NULL,
    date DATE NOT NULL,
    time TEXT NOT NULL
);

-- Enable RLS for announcements
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Allow read/write access for demonstration
CREATE POLICY "Allow public access to announcements" ON public.announcements
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);
